#!/usr/bin/exec-suid --real -- /usr/bin/python -I
import sys
sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

# Add your imports and other code below here
import subprocess
import re

def main(filename:str):
    
    fake_input = "1 2 3 4 5"

    results = subprocess.run(filename, input=fake_input, capture_output=True, text=True)
    numResult = re.search("-?[0-9]{1,19} -?[0-9]{1,19} -?[0-9]{1,19} -?[0-9]{1,19} -?[0-9]{1,19}", results.stdout)
    if not numResult:
        errorCheck = re.search("-?[0-9]{1,19}( |\n)?-?[0-9]{1,19}( |\n)?-?[0-9]{1,19}( |\n)?-?[0-9]{1,19}( |\n)?-?[0-9]{1,19}( |\n)?", results.stdout)
        if not errorCheck:
            print("ERROR: Unknown problem; please ensure your output is all on one line and separated by spaces.")
        else:
            print("ERROR: Your numbers are not on one line, update your code and try again.")
        sys.exit(0)
    
    print("Congratulations!")
    print_flag()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("ERROR: Missing file to verify, exiting.")
        sys.exit(0)

    main(sys.argv[1])