#!/usr/bin/exec-suid --real -- /usr/bin/python -I
import sys
sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

# Add your imports and other code below here
import subprocess
import os
import re

def main(filename: str):
    
    # command = "/home/hacker/Documents/" + filename
    command = "./"+filename
    results = subprocess.run(command,capture_output=True, text=True)
    
    if 3 != str.count(results.stdout, "\n"):
        print("ERROR: You must print three things to the screen. Try again!")
        sys.exit(0)

    boolResult = re.search("(true|false)", results.stdout)
    if not boolResult:
        print("ERROR: Missing boolean value in output, try again!")
        sys.exit(0)

    intResult = re.search("-?[0-9]{1,19}", results.stdout)
    # max.intValue for go program - 9223372036854775807 (2^63)
    if not intResult:
        print("ERROR: Missing int value in output, try again!")
        sys.exit(0)

    stringResult = re.search("[a-zA-Z]*", results.stdout)
    if not stringResult:
        print("ERROR: Missing string value in your output, try again!")
        sys.exit(0)

    print("Congratulations!")
    print_flag()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("ERROR: Missing file to verify, exiting.")
        sys.exit(0)
    
    if sys.argv[1].count("/") != 0:
        print("ERROR: Only supply the name of your file, exiting.")
        sys.exit(0)

    main(sys.argv[1])